GET http://localhost:3310/api/users

###

GET http://localhost:3310/api/users/1

###

POST http://localhost:3310/api/users HTTP/1.1
content-type: application/json

{
  "firstname": "John",
  "lastname": "Do",
  "email": "johndoe@gmail.com",
  "password": "password",
  "github_url": "github",
  "linkedin_url": "linkedin",
  "profil_img": "johndo.png"
}

###

PUT http://localhost:3310/api/users/2 HTTP/1.1
content-type: application/json

{
  "firstname": "popo",
  "lastname": "pipi",
  "email": "pupu@gmail.com",
  "password": "tata",
  "github_url": "github",
  "linkedin_url": "linkedin",
  "level": 2,
  "register_date": "2025/01/10",
  "profil_img": "coucou",
  "is_admin": true
}

###

DELETE http://localhost:3310/api/users/3

###

GET http://localhost:3310/api/videos

###

GET http://localhost:3310/api/videos/5

###

POST http://localhost:3310/api/videos HTTP/1.1
content-type: application/json

{
  "name": "pupu",
  "duration": "10",
  "thumbnail": "/assets/videos/Quest-Welcomonboard(part1).mp4",
  "descrition": "Quelle belle video !",
  "category_id": 3,
  "preview_image":"popo",
  "is_freemium": false,
  "added_date": "2025-11-01",
  "is_heroSlide": true,
  "is_popular": true
}

###

PUT http://localhost:3310/api/videos/2 HTTP/1.1
content-type: application/json

{
  "name": "pupu",
  "duration": "10",
  "thumbnail": "/assets/videos/Quest-Welcomonboard(part1).mp4",
  "descrition": "Encore plus de videos !",
  "category_id": 3,
  "is_freemium": false,
  "added_date": "2025-11-01",
  "is_heroSlide": true,
  "is_popular": true
}

###
DELETE http://localhost:3310/api/videos/3

###

GET http://localhost:3310/api/categories

###

GET http://localhost:3310/api/category/6

###

POST http://localhost:3310/api/categories HTTP/1.1
content-type: application/json

{"name": "pupu"}

